import matplotlib.pyplot as plt

# Sample revenue data in millions of USD (approximate figures)
companies = ['Red Hat', 'GitLab', 'MongoDB', 'Elastic', 'HashiCorp']
revenues = [3000, 330, 1570, 608, 320]  # in millions USD

# Create the bar chart
plt.figure(figsize=(10, 6))
bars = plt.bar(companies, revenues, color='skyblue')

plt.xlabel('Company')
plt.ylabel('Revenue (in Million USD)')
plt.title('Revenue Generated by Leading Open Source Companies')
plt.ylim(0, max(revenues) * 1.2)

# Annotate the bars with revenue values
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 50, f'{height}', 
             ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.savefig('revenue_chart.png')